### ISSUE TITLE
A filter to block web workers by default

### ISSUE THREAD

**Issue by adranger** [adranger/web-workers-whitelist#1]
@krystian3w @THEtomaso @smed79 

What do you think of this? It blocks web workers everywhere except for whitelisted domains where they are explicitly needed. I find it an obviously easier solution than trying to keep up with every new mining domain.

Tell me if you're interested in using it and helping to expand it with the sites you use, so I can add you as collaborators. If it grows to cover a larger set of sites, maybe they'll add it to one of the big repositories.

**Comment by THEtomaso** [comment]
Try posting your idea here:
https://github.com/DandelionSprout/adfilt/issues/7/

**Comment by THEtomaso** [comment]
@adranger:
Thanks for the invite that you sent me, but I don't feel quite up to working on this stuff.

**Comment by adranger** [comment]
@THEtomaso that's fine. It was just for you to add the sites you use in case you wanted to subscribe.

@krystian3w This technology is used to perform processor-intensive actions on your browser. Most of the legit uses I've found were video players. It is good to block it by default, though, because it can also be used to secretly do things like this: https://comparic.pl/strona-organizacji-non-profit-make-wish-zainfekowana-nielegalnie-kopala-kryptowaluty/

@uBlock-user you might like this.

**Comment by uBlock-user** [comment]
Certainly useful to counter mining and other such intrusive scripts that don't care for user-consent. I don't have a list as I use uMatrix which has _Forbid-web-workers_ switch to take care of this. You can start with `google.com` for recaptcha.
